apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: mycluster2_v1alpha2
  namespace: jkolaric-01
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: tanzu-sp
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-small
      storageClass: tanzu-sp
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55

